wandb_version: 1

train:
  desc: null
  value: true
lr:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 1
output_dir:
  desc: null
  value: model_checkpoints/
plot:
  desc: null
  value: false
model_checkpoint:
  desc: null
  value: model_checkpoints/trained_model.pt
test:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704709970.806312
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
