wandb_version: 1

train:
  desc: null
  value: true
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
output_dir:
  desc: null
  value: model_checkpoints/
plot:
  desc: null
  value: false
model_checkpoint:
  desc: null
  value: model_checkpoints/trained_model.pt
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704552206.828039
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
