wandb_version: 1

train:
  desc: null
  value: true
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
output_dir:
  desc: null
  value: model_checkpoints/
plot:
  desc: null
  value: false
model_checkpoint:
  desc: null
  value: model_checkpoints/trained_model.pt
test:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704732119.049384
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 2
      - 3
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      3:
      - 16
      - 23
      4: 3.10.0
      5: 0.16.1
      6: 4.33.2
      8:
      - 3
      - 5
      13: windows-amd64
