wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704707248.216704
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: logits._type
      5: 1
      6:
      - 1
    - 1: logits.values
      5: 1
      6:
      - 1
    - 1: logits.bins
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
